# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b22c88d4d08f251330da6fde0f90ae6e99ade44398cd7aa0bbeb030af3860e93a0379f49ae06b792437a38450575ca76621296dbf32eaf723a734641661cca8d

test:
  secret_key_base: 947766679d23645c80442cf8192d4cef4d1b038e0ae29b054cd7283b654cd4dd0f7908a475e85f1cb2eb4685fbb06dc115a98ff11cea8d247b1c11c67e5b3b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
